version: "3.8"

services:
  database:
    image: postgres:16-alpine
    container_name: dev-postgresql
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=dslist
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - dev-network
volumes:
  data:
networks:
  dev-network:
    driver: bridge